version: "3.4"
services:
  api:
    container_name: express_api
    stdin_open: false
    tty: true 
    build: 
      context: .
      dockerfile: ops/docker/Dockerfile
    volumes:
      - ./:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 3001:3000
    depends_on: 
      - db
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    entrypoint: yarn dev
  db:
    container_name: express_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=express_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
    db:
      driver: local